name: Python Flask CI / CD

on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: docker/build-push-action@v1
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    # You can test your matrix by printing the current Python versions***
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: docker build -t pythonflask .
    - name: Push
      run: |
          docker push ${{ secrets.DOCKER_USER }}/pythonflask:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/pythonflask:latest
